[colors.bright]
black = "#424242"
blue = "#b6d6fd"
cyan = "#4fb8cc"
green = "#5fd7a7"
magenta = "#6855de"
red = "#e32791"
white = "#ffffff"
yellow = "#f3e430"

[colors.cursor]
cursor = "#fa008e"
text = "#05ff93"

[colors.normal]
black = "#212121"
blue = "#008ec4"
cyan = "#20a5ba"
green = "#10a778"
magenta = "#523c79"
red = "#c30771"
white = "#f1f1f1"
yellow = "#a89c14"

[colors.primary]
background = "#212121"
foreground = "#f1f1f1"

[cursor]
blink_interval = 250
[cursor.style]
shape = "Block"
blinking = "Always"

[font]
size = 13

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_padding = false
decorations = 'None'
opacity = 0.9

[window.padding]
x = 2
y = 2

[keyboard]
bindings = [
  { key = "Key6", mods = "Control", chars = "\u001e" }
]
