#! /bin/sh

# Set topbar
INTERNAL_MONITOR='eDP1'
EXTERNAL_MONITOR='DP3-8'

# on first load setup default workspaces
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  bspc monitor "$EXTERNAL_MONITOR" -d I II III IV V VI VII VIII IX
  bspc monitor "$INTERNAL_MONITOR" -d X
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
  bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
fi

monitor_add() {
  # Move first 5 desktops to external monitor
  for desktop in $(bspc query -D --names -m "$INTERNAL_MONITOR" | sed 9q); do
    bspc desktop "$desktop" --to-monitor "$EXTERNAL_MONITOR"
  done

  # Remove default desktop created by bspwm
  bspc desktop Desktop --remove

  # reorder monitors
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
}

monitor_remove() {
  # Add default temp desktop because a minimum of one desktop is required per monitor
  bspc monitor "$EXTERNAL_MONITOR" -a Desktop

  # Move all desktops except the last default desktop to internal monitor
  for desktop in $(bspc query -D -m "$EXTERNAL_MONITOR");	do
    bspc desktop "$desktop" --to-monitor "$INTERNAL_MONITOR"
  done

  # delete default desktops
  bspc desktop Desktop --remove

  # reorder desktops
  bspc monitor "$INTERNAL_MONITOR" -o I II III IV V VI VII VIII IX X
}


if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  # set xrandr rules for docked setup
  sh ~/.screenlayout/multi_monitor.sh
  if [[ $(bspc query -D -m "${EXTERNAL_MONITOR}" | wc -l) -ne 9 ]]; then
    monitor_add
  fi
  bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"
else
  # set xrandr rules for mobile setup
  sh ~/.screenlayout/single_monitor.sh
  if [[ $(bspc query -D -m "${INTERNAL_MONITOR}" | wc -l) -ne 10 ]]; then
    monitor_remove
  fi
fi


bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
# bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
# bspc config merge_overlapping_monitors true

bspc config border_width         3
bspc config window_gap          0
bspc config split_ratio          0.52

bspc config focused_border_color        "#e6c587"
bspc config normal_border_color         "#444444"
bspc config active_border_color         "#444444"

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a chromium desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on state=monocle
bspc rule -a mysql-workbench desktop='^4' follow=on
bspc rule -a spotify desktop='^7' follow=on
bspc rule -a steam desktop='^8' follow=on
bspc rule -a Slack desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor layout
# 
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet  &

# Map Esc (press) and CTRL (hold) to Caps key
pkill xcape
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

