#! /bin/sh
#
source ~/.zshrc

###########################################
# MONITOR CONFIG

INTERNAL_MONITOR="${MONITOR_NAME:-eDP1}"
EXTERNAL_MONITOR="$(xrandr -q | grep -w connected |\
  grep -v -w ${INTERNAL_MONITOR} | awk '{print $1}' | head -1)"

# on first load setup default workspaces
if [[ $(xrandr -q | grep "${EXTERNAL_MONITOR} connected") ]]; then
  bspc monitor "$EXTERNAL_MONITOR" -d I II III IV V VI VII VIII IX
  bspc monitor "$INTERNAL_MONITOR" -d X
  # bspc wm -O "$INTERNAL_MONITOR" "$EXTERNAL_MONITOR"
else
  bspc monitor "$INTERNAL_MONITOR" -d I II III IV V VI VII VIII IX X
fi

###########################################
# BSPWM CONFIG
bspc config borderless_monocle   true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false

# bspc config remove_disabled_monitors true
# bspc config remove_unplugged_monitors true
# bspc config merge_overlapping_monitors true

bspc config border_width         3
bspc config window_gap          0
bspc config split_ratio          0.52
bspc config top_padding 30

bspc config focused_border_color        "#e6c587"
bspc config normal_border_color         "#444444"
bspc config active_border_color         "#444444"


bspc rule -a Postman desktop '^2'
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a chromium desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on state=monocle
bspc rule -a mysql-workbench desktop='^4' follow=on
bspc rule -a spotify desktop='^7' follow=on
bspc rule -a steam desktop='^8' follow=on
bspc rule -a Slack desktop='^9'
# bspc rule -a Screenkey manage=off

###########################################
# AUTOSTART
pgrep -x sxhkd > /dev/null || sxhkd &

# Network Applet
# nm-applet  &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
# dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

# Picom
picom -CGb &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

###########################################
# MAPPINGS
# Map Esc (press) and CTRL (hold) to Caps key
pkill xcape
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &

# Cursor
xsetroot -cursor_name left_ptr &


