#! /bin/sh

# Set topbar
monitor_list=$(xrandr --query | grep " connected" | cut -d" " -f1)
monitor_count=$(echo $monitor_list | wc -l)
for m in $monitor_list; do
  if [ $m == 'eDP1' ]; then
    if [ $monitor_count == 1 ]; then
      bspc monitor -f eDP1
      bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
    fi
  else
    bspc monitor $m -d I II III IV V VI VII VIII IX
  fi
done

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

bspc config border_width         3
bspc config window_gap          0
bspc config split_ratio          0.52

bspc config focused_border_color        "#e6c587"
bspc config normal_border_color         "#444444"
bspc config active_border_color         "#444444"

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a chromium desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on state=monocle
bspc rule -a mysql-workbench desktop='^4' follow=on
bspc rule -a spotify desktop='^7' follow=on
bspc rule -a steam desktop='^8' follow=on
bspc rule -a Slack desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Autostart
pgrep -x sxhkd > /dev/null || sxhkd &

# Monitor layout
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet  &

# Map Esc (press) and CTRL (hold) to Caps key
pkill xcape
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

