#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true
bspc config merge_overlapping_monitors true
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

# Set display from arandr saved script
monitor_count=$(sh ~/.screenlayout/grep_connected_monitor_count.sh)
if [[ $monitor_count == 1 || -z "$monitor_count"  ]]
then
  echo single monitor > ~/log.txt
  bspc monitor -f eDP1
  bspc monitor eDP1 -d I II III IV V VI VII VIII IX X
else
  echo double monitor > ~/log.txt
  bspc monitor -f DP3
  bspc monitor DP3 -d I II III IV V VI VII VIII IX
  bspc monitor eDP1 -d X
fi

bspc config border_width         5
bspc config window_gap          7

# bspc config split_ratio          0.52

bspc rule -a Gimp desktop='^6' state=floating follow=on
bspc rule -a Brave-browser desktop='^3' follow=on
bspc rule -a chromium desktop='^3' follow=on
bspc rule -a firefox desktop='^3' follow=on
bspc rule -a mysql-workbench desktop='^5' follow=on
bspc rule -a Slack desktop='^9'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#aabbaa"
bspc config normal_border_color         "#444444"
bspc config active_border_color         "#444444"

#
# Autostart
#
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  
# Picom
picom -CGb &
# Network Applet
nm-applet  &

# Map Esc (press) and CTRL (hold) to Caps key
setxkbmap -option 'caps:ctrl_modifier' && xcape -e 'Caps_Lock=Escape' -t 150 &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

